spring:
  application:
    name: talentops

  profiles:
    active: dev

keycloak:
  server-url: http://localhost:8080
  realm: talentops

  resource-client:
    client-id: talentops-backend

  admin-client:
    client-id: admin-client
    client-secret: KnrNZfEDmgw8cnznDyCYSw0Yua6gzyeV



